### PR TITLE
fix something with avb2.0, my device is nubia nx606j 

### PR DESCRIPTION
**Pull request by 18712886438**

### CODE REVIEW

**Comment by cfig** [comment]
Dear Super,
I see you changed maxHeapSize from '512m' to '4096m', do you have a huge image to sign in this case? What's its original size?
Just curious :)

**Comment by 18712886438** [comment]
> Dear Super,
> I see you changed maxHeapSize from '512m' to '4096m', do you have a huge image to sign in this case? What's its original size?
> Just curious :)

Just to sign my NX606J's stock kernel , about 67MB I think.
BTW, are u Chinese?

**Comment by cfig** [comment]
是

**Comment by 18712886438** [comment]
>  是

那还说啥,老哥联系方式给个啊

**Comment by cfig** [comment]
又不是泡妞，急啥, 技术问题，直接邮件吧，yuyezhong@gmail.com. 我还有些问题问下，了解下nx606j

**Pull request merged**
